### ISSUE TITLE
Find the top 4/5 phone number patterns in every city.

### ISSUE THREAD

**Issue by anantharam** [rohitmanglik/data-enrichment#56]
We need to write a code to figure out the common patterns in phone numbers in every city and sort them by their frequency of occurance.
We can then get the ops team to call the top 4/5 patterns to figure out if any of them are virtual phone numbers so that we can remove those patterns completely from our csv files..

**Comment by anantharam** [comment]
@rohitmanglik Please assign this issue to appropriately based on people's current load.

**Comment by rohitmanglik** [comment]
Verified the fix, it works great. 

How the question is: how to remove those entries. It should be dealt in new script after Beta release.
