### ISSUE TITLE
Install dependencies automatically

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#64]
Our code should be able to install all dependencies automatically. 

There are many tools for that. e.g. For JS we have bower.

**Comment by shubhiD** [comment]
pip install -r requirements.txt

It will download everything mentioned in requirements.txt

Is this what is required?

**Comment by rohitmanglik** [comment]
Yes, please update it in documentation.

Also, after running it on our new server, it's showing some error. We need to make areangements for that as well.

**Comment by rohitmanglik** [comment]
I was getting following error:
`/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.`

It was resolved by installing following dependency:
`pip install pyopenssl ndg-httpsclient pyasn1`

**Comment by rohitmanglik** [comment]
Any update?

**Comment by shubhiD** [comment]
Please review readme, i have updated it
