### ISSUE TITLE
Download Images

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#72]
Step 1: Download images in Images Column
Step 2: Hash {imageid-eduid} and save all the images in images folder (e.g. 289qhfbvglerigvb347ovblisdjn.jpg)
Step 3: rename the url to new name. 

e.g. http://googleusercontent.com/somthing.jpg, http://googleusercontent.com/foo.jpg
will convert to
lvaniuvjneibbwiu894rjf43u.jpg, niarlgvb4398gtbn.jpg

**Comment by pinakinathc** [comment]
added a code that solves this but some images are not getting displayed. Also printed a list of image urls that urllib method fails to download.
[https://github.com/rohitmanglik/data-enrichment/commit/25f1e4e35794f795dff1d920890e22789d350e78](url)
this has one deletion of line that should not have been made. Fixed it in the next commit.

**Comment by rohitmanglik** [comment]
Please merge it in main code.

**Comment by rohitmanglik** [comment]
Working fine in production.
