### ISSUE TITLE
Merge Utilities

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#73]
We have five utilities to be run to come with a finalized folder. Except post_validate_email.py, all the utilities can be merged. 
You may have to create an intermediary folder "tmp" to save preprocessed and updated files. 

Merge following four utilities into main.py:

1) addUniqueId.py - User should explicitly define a starting point.
2) joinCSV.py
3) removeInterDuplicates.py
4) save_img.py

**Comment by shashwat-vik** [comment]
As per the discussion, the merged utilities include:

- post_validate_email.py
- removeInterDuplicates.py
- joinCSV.py

They form the Layer 2, that would be run locally.
Also, the utility **normalize_city_name.py** is moved to run in main.py as it forms the Layer 1.
