### ISSUE TITLE
Full Address data if no data from Google Places.

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#75]
If we don't get any data from Google Places, do we still update Full Address based on input data?

**Comment by shashwat-vik** [comment]
'fullAddress' suffers a conflict.
Its getting updated at 2 places.

1) In autoComplete.py, it is updated only if we get data from Google Places.
2) In geocodertest.py, it is updated by concatenating data already existing in columns everytime.

So 2 overrides 1 in all cases, making it noisy.
Will it be ok, if 2 happens only when no data comes from Google Places ?

**Comment by rohitmanglik** [comment]
Yes, definitely.

Also, if FB data is available and Google Place id is not present, we can override fullAddress with address provided by FB.

**Comment by shashwat-vik** [comment]
Full Address is updated by **autoComplete.py** firstly. If data is not available from it, existing data in csv columns is concatenated to make the Full Address.

This concatenation happens in **_'_addGeocoding'_** in **geocodertest.py** which is made to run after **fbGraph.py**. If fbGraph gets the address details, it repairs the necessary columns respectively.

Thus fbGraph's data would be reflected during the concatenation, if autoComplete data is not obtained.
