### ISSUE TITLE
City data is inconsistent

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#76]
City data is inconsistent for Kolkata, Delhi, Cochin etc.

**Comment by shashwat-vik** [comment]
This inconsistency is a result of 2 cases.
1) Confusion over parameter that result in District vs City
2) Union Territory Cases

Both are addressed in 	8d9873d

**Comment by shashwat-vik** [comment]
Still it would suffer inconsistency.
Not because of data being wrong. But due to official name and local name conflict.
E.g. Bengaluru (when autocomplete works) and Bangalore (otherwise)

Which convention you wanna follow to group the listings based on City ?

**Comment by rohitmanglik** [comment]
New names in most of the cases- Bengaluru and Kolkata

Exceptions:
Gurgaon over Gurugram- not sure if the next Govt will change it back.

Delhi - Union Territory is preferred in this case.

**Comment by rohitmanglik** [comment]
Might be we can have a reference csv file for this. Everytime we update city, our code will look into all aliases and update accordingly.

**Comment by shashwat-vik** [comment]
Both the situations of new names and exceptions can be generically updated in **alias_data.csv** so that city names are consistent.
