### ISSUE TITLE
slkh_tmp and slkh_others_tmp data duplication

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#77]
Is the data of slkh_tmp and slkh_others_tmp different? Are we sure there is no duplication in both of them?

If there is duplication, we have to remove coinciding entries from slkh_others_tmp folder.

**Comment by pinakinathc** [comment]
execute:
`python duplicate.py`
to see details.

**Comment by pinakinathc** [comment]
This is the output on execution of the code:

`The following data are for sulekha_temp:

number of Same folder entries repeat:  1485
total:  32092
total number of files:  48
finished building central dictionary:

#############
The following are for sulekha_other_temp:

number of Same entries in sulekha_other_temp:  58761
total:  85839
total number of files:  48
End of execution

number of same entries: 5054


Sulekha_temp distinct entries:  30607

Sulekha_other_temp distinct entries:  27078
`

**Comment by pinakinathc** [comment]
@anantharam can you please help me out. I am a bit confused with these results.

**Comment by rohitmanglik** [comment]
@anantharam @shashwat-vik Please verify

**Comment by pinakinathc** [comment]
@anantharam @shashwat-vik when i am executing this file separately it is not giving any kind of warning.

**Comment by anantharam** [comment]
@pinakinathc Can we close this issue now?

**Comment by pinakinathc** [comment]
@anantharam yeah sure :)
