### ISSUE TITLE
Updated sulekha_others

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/data-enrichment#78]
1) We have to remove duplicates i.e. delete the entries already uploaded in sulekha_tmp  - issue#77 - Waiting for Anant.

2) There is a file updated_scrap4_mumbai.csv. It doesn't follow pattern of other cities.  If we don't include updated_sample_big.csv, updated_sample.csv and updated_scrap4_mumbai.csv, we have only 47 files. One file is missing.

3) Verify whether City data of cities starting with a,b and c is correct. If not, please rerun the jobs.

**Comment by pinakinathc** [comment]
@rohitmanglik @anantharam please review this code. Hope it works fine. Just removed entries that were already present in sulekha_temp i.e. removed total of 5054 entries.

**Comment by anantharam** [comment]
@pinakinathc You were supposed to remove the entries from sulekha_others_temp not sulekha_temp, right?

**Comment by rohitmanglik** [comment]
@pinakinathc @anantharam is this issue resolved?

**Comment by pinakinathc** [comment]
@anantharam  I rechecked the code and it seems I updated the new files of sulekha_other_temp in the output folder. Maybe I am overlooking something. Can you please help me a bit. :)

**Comment by pinakinathc** [comment]
i was running the new files of sulekha_other_temp and while running scrap_jamshedpur.csv I encountered with this warning.

`Current file is ./input/scrap_jamnagar.csv


RUNNING AUTOCOMPLETE
STATE :  Gujarat
####################
VERIFIED     :  14
NOT VERIFIED :  22
####################

UPDAING ADDRESS
Permanently closed is  Xplora Design Skool [Address Unverified]
Permanently closed is  Xplora Design Skool [Address Unverified]
viewports for  2

REMOVED INTRA-DUPLICATES :  0

Adding photos...please wait...

No of place id ->14
Fetching info from FB Graph
STATE :  Gujarat

New Info Added from Facebook
Details:0 Facebook Link:13 Cover:13
Website:1 Pincode:1 Address:2 Images:13 Verified 0/13 Phone:13 Emails:13
ADDING GEOCODES...
Total precise entries: 9 out of 22
Bad Phone number 0228-2712374 Deleted...
Bad Phone number 001-608-218-3798() Deleted...
Bad Phone number :+918008009704 Deleted...
Total 36 threads are running
Total Rejected: 1 Total Accepted: 34 Total Missed: 34
Writing to CSV...
***Successfully processed 5 files.***
Initial size of records6739
Final size of records2495
T/home/user/pinaki/data-enrichment/fbGraph.py:122: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if website == self.website_parser(resp):
otal meregers: 4244
`

Please see the last few lines. Should this be a reason of concern.

**Comment by pinakinathc** [comment]
Found this error while executing scrap_kolkata.csv in previous commit: 77d84b0 I tried to fix it.
Running the latest code on the last set of files.

`Traceback (most recent call last):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 482, in processAll
    node = self.searchPlace(row,state)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 228, in searchPlace
    node=self.analyze_prediction(row,query,True)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 176, in analyze_prediction
    if self.match_phone_nos(phones, safe_dec_enc(place['phone'])):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 141, in match_phone_nos
    resp_nos[i] = resp_nos[i].encode('ascii',errors='ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
12/20/2016 11:06:58 PM ERROR: Error loading information from facebook for DoOnDid
Traceback (most recent call last):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 482, in processAll
    node = self.searchPlace(row,state)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 231, in searchPlace
    node = self.analyze_prediction(row,query,False)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 176, in analyze_prediction
    if self.match_phone_nos(phones, safe_dec_enc(place['phone'])):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 141, in match_phone_nos
    resp_nos[i] = resp_nos[i].encode('ascii',errors='ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 13: ordinal not in range(128)
12/20/2016 11:59:57 PM ERROR: Error loading information from facebook for Global Technologies
Traceback (most recent call last):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 482, in processAll
    node = self.searchPlace(row,state)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 231, in searchPlace
    node = self.analyze_prediction(row,query,False)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 176, in analyze_prediction
    if self.match_phone_nos(phones, safe_dec_enc(place['phone'])):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 141, in match_phone_nos
    resp_nos[i] = resp_nos[i].encode('ascii',errors='ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
12/21/2016 12:46:10 AM ERROR: Error loading information from facebook for Karrox
Traceback (most recent call last):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 482, in processAll
    node = self.searchPlace(row,state)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 228, in searchPlace
    node=self.analyze_prediction(row,query,True)
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 176, in analyze_prediction
    if self.match_phone_nos(phones, safe_dec_enc(place['phone'])):
  File "/home/user/pinaki/data-enrichment/fbGraph.py", line 141, in match_phone_nos
    resp_nos[i] = resp_nos[i].encode('ascii',errors='ignore')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
`
