### ISSUE TITLE
merging teachers data

### ISSUE THREAD

**Issue by ShashiPrakash88** [rohitmanglik/data-enrichment#82]
this is regarding the teachers data csv files.

if possible can anyone merge all the columns of one teacher into a single column in a **serialized** manner.
and make this for all the teacher in one school.

i.e all the teachers of one school are in one row so that it is  easier for merging in the main dataset and  also for importing it.

for eg. if a school has 10 teachers then there will be 10 columns, one for each teacher. each column containing all the data about the teacher in a **serialized** way. so that for one school one row is for all teachers with number of columns same as the number of teachers in that school.

these rows then will be merged in the main dataset according to their school code.

if you have any issues regarding this issue feel free to contact me.

**Comment by jishnujayakumar** [comment]
I have made a utility for this task and the output has been handed over to @ShashiPrakash88 on 15-07-2017. The output was tested and confirmed ok by @ShashiPrakash88.
